from typing import List, Optional
from uuid import UUID
from fastapi import APIRouter, Depends, status, BackgroundTasks
from fastapi.encoders import jsonable_encoder

from app.api.dependencies import (
    CurrentUser,
    DbSession,
    require_permission,
)
from app.models.agent import Alert, AgentAction, AlertStatus
from app.schemas.agent import AlertResponse, AgentActionResponse
from app.schemas.auth import OrganizationResponse
from app.workflows.daily_analysis import DailyAnalysisWorkflow
from app.utils.responses import success_response
from sqlalchemy import select, desc

router = APIRouter(prefix="/agents", tags=["Agents"])

@router.get(
    "/actions",
    status_code=status.HTTP_200_OK,
    response_model=List[AgentActionResponse],
    summary="List agent actions",
    dependencies=[Depends(require_permission("agents:read"))],
)
async def list_agent_actions(
    user: CurrentUser,
    db: DbSession,
    limit: int = 50,
    assigned_to_me: bool = False,
):
    """
    List recent actions taken by the AI agents.
    
    - **assigned_to_me**: If true, returns only actions for patients assigned to the current user (Physician, Nurse, or Coordinator).
    """
    from app.models.patient import Patient
    from sqlalchemy import or_
    
    query = select(AgentAction).join(AgentAction.patient).where(
        AgentAction.organization_id == user.organization_id
    )
    
    if assigned_to_me:
        query = query.where(
            or_(
                Patient.primary_physician_id == user.id,
                Patient.assigned_nurse_id == user.id,
                Patient.care_coordinator_id == user.id
            )
        )
        
    query = query.order_by(desc(AgentAction.created_at)).limit(limit)
    
    result = await db.execute(query)
    actions = result.scalars().all()
    
    return success_response(
        status_code=200,
        message="Agent actions retrieved",
        data=jsonable_encoder(actions),
    )

@router.get(
    "/alerts",
    status_code=status.HTTP_200_OK,
    response_model=List[AlertResponse],
    summary="List active alerts",
    dependencies=[Depends(require_permission("alerts:read"))],
)
async def list_alerts(
    user: CurrentUser,
    db: DbSession,
    status: AlertStatus = AlertStatus.PENDING,
    limit: int = 50,
):
    """List pending or active alerts generated by agents."""
    query = select(Alert).where(
        Alert.organization_id == user.organization_id,
        Alert.status == status
    ).order_by(desc(Alert.created_at)).limit(limit)
    
    result = await db.execute(query)
    alerts = result.scalars().all()
    
    return success_response(
        status_code=200,
        message="Alerts retrieved",
        data=jsonable_encoder(alerts),
    )

@router.post(
    "/trigger-rounds",
    status_code=status.HTTP_202_ACCEPTED,
    summary="Trigger daily analysis",
    dependencies=[Depends(require_permission("agents:trigger"))],
)
async def trigger_analysis_rounds(
    background_tasks: BackgroundTasks,
    user: CurrentUser,
    db: DbSession,
):
    """Manually trigger a morning rounds analysis for the organization."""
    workflow = DailyAnalysisWorkflow(db)
    background_tasks.add_task(workflow.execute_for_org, user.organization_id)
    
    return success_response(
        status_code=202,
        message="Analysis rounds triggered in background",
    )

@router.patch(
    "/config",
    status_code=status.HTTP_200_OK,
    response_model=OrganizationResponse,
    summary="Update agent configuration",
    dependencies=[Depends(require_permission("org:update"))],
)
async def update_agent_config(
    user: CurrentUser,
    db: DbSession,
    disease_specializations: List[str],
):
    """Update which diseases the agents should monitor for this organization."""
    organization = user.organization
    organization.disease_specializations = disease_specializations
    
    db.add(organization)
    await db.commit()
    await db.refresh(organization)
    
    return success_response(
        status_code=200,
        message="Agent configuration updated",
        data=jsonable_encoder(organization),
    )
