"""add_appointment_reminder_and_decision_trace

Revision ID: 2bad71f1cfde
Revises: b4859c1ee12f
Create Date: 2026-01-22 12:34:45.095849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bad71f1cfde'
down_revision: Union[str, Sequence[str], None] = 'b4859c1ee12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('call_type', sa.Enum('OUTBOUND_REMINDER', 'OUTBOUND_FOLLOWUP', 'OUTBOUND_ALERT', 'OUTBOUND_MANUAL', 'INBOUND', name='calltype'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'RINGING', 'ANSWERED', 'COMPLETED', 'FAILED', 'NO_ANSWER', 'BUSY', 'CANCELLED', name='callstatus'), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_sessions_call_type', 'call_sessions', ['call_type'], unique=False)
    op.create_index('idx_call_sessions_started_at', 'call_sessions', ['started_at'], unique=False)
    op.create_index('idx_call_sessions_status', 'call_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_call_sessions_organization_id'), 'call_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_patient_id'), 'call_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_room_name'), 'call_sessions', ['room_name'], unique=True)
    op.create_table('appointment_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduled_send_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'FAILED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_by_agent', sa.String(length=50), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminder_org_status', 'appointment_reminders', ['organization_id', 'status'], unique=False)
    op.create_index('idx_reminder_scheduled_status', 'appointment_reminders', ['scheduled_send_time', 'status'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_appointment_id'), 'appointment_reminders', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_idempotency_key'), 'appointment_reminders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_appointment_reminders_organization_id'), 'appointment_reminders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_patient_id'), 'appointment_reminders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_scheduled_send_time'), 'appointment_reminders', ['scheduled_send_time'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_status'), 'appointment_reminders', ['status'], unique=False)
    op.add_column('agent_actions', sa.Column('decision_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('appointments', sa.Column('priority_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('appointments', sa.Column('no_show_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('appointments', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_appointments_priority_level'), 'appointments', ['priority_level'], unique=False)
    op.add_column('patients', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'timezone')
    op.drop_index(op.f('ix_appointments_priority_level'), table_name='appointments')
    op.drop_column('appointments', 'reminder_sent_at')
    op.drop_column('appointments', 'no_show_count')
    op.drop_column('appointments', 'priority_level')
    op.drop_column('agent_actions', 'decision_trace')
    op.drop_index(op.f('ix_appointment_reminders_status'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_scheduled_send_time'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_patient_id'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_organization_id'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_idempotency_key'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_appointment_id'), table_name='appointment_reminders')
    op.drop_index('idx_reminder_scheduled_status', table_name='appointment_reminders')
    op.drop_index('idx_reminder_org_status', table_name='appointment_reminders')
    op.drop_table('appointment_reminders')
    op.drop_index(op.f('ix_call_sessions_room_name'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_patient_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_organization_id'), table_name='call_sessions')
    op.drop_index('idx_call_sessions_status', table_name='call_sessions')
    op.drop_index('idx_call_sessions_started_at', table_name='call_sessions')
    op.drop_index('idx_call_sessions_call_type', table_name='call_sessions')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
