"""add_phone_settings_to_org

Revision ID: 31f012af3382
Revises: 33e0609eca73
Create Date: 2026-01-26 17:38:31.888733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31f012af3382'
down_revision: Union[str, Sequence[str], None] = '33e0609eca73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('agent_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'agent_settings')
    op.drop_column('organizations', 'phone_settings')
    # ### end Alembic commands ###
