"""add_appointment_type_column

Revision ID: 3c6d8bc5a36c
Revises: 3b209906a533
Create Date: 2026-01-27 17:22:43.694274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3c6d8bc5a36c'
down_revision: Union[str, Sequence[str], None] = '3b209906a533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # --- FIX 1: Create the Enum Type safely before using it ---
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'visitmode') THEN
                CREATE TYPE visitmode AS ENUM ('IN_PERSON', 'TELEHEALTH');
            END IF;
        END$$;
    """)
    # --------------------------------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns (Using server_default to prevent crashes if table has data)
    op.add_column('appointments', sa.Column('appointment_type', sa.String(length=100), server_default='General', nullable=False))
    op.add_column('appointments', sa.Column('visit_mode', sa.Enum('IN_PERSON', 'TELEHEALTH', name='visitmode'), server_default='IN_PERSON', nullable=False))
    
    # Remove the server_defaults now that columns exist
    op.alter_column('appointments', 'appointment_type', server_default=None)
    op.alter_column('appointments', 'visit_mode', server_default=None)

    # Renaming 'type' to 'appointment_type' - dropping old column
    op.drop_column('appointments', 'type')
    
    # --- SAFETY FIX: I commented these out because your code USES these fields! ---
    # If you drop them, your app will crash when you check 'no_show_count'.
    # op.drop_index(op.f('ix_appointments_priority_level'), table_name='appointments')
    # op.drop_column('appointments', 'no_show_count')
    # op.drop_column('appointments', 'reminder_sent_at')
    # -----------------------------------------------------------------------------
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore the deleted columns if we roll back
    # (Uncommented these since we commented out the drops above, but keeping structure valid)
    # op.add_column('appointments', sa.Column('reminder_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # op.add_column('appointments', sa.Column('no_show_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # op.create_index(op.f('ix_appointments_priority_level'), 'appointments', ['priority_level'], unique=False)
    
    op.add_column('appointments', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    
    op.drop_column('appointments', 'visit_mode')
    op.drop_column('appointments', 'appointment_type')
    
    # Optional: cleanup type
    op.execute("DROP TYPE IF EXISTS visitmode")
    # ### end Alembic commands ###