"""add_appointment_type_column

Revision ID: 3c6d8bc5a36c
Revises: 3b209906a533
Create Date: 2026-01-27 17:22:43.694274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c6d8bc5a36c'
down_revision: Union[str, Sequence[str], None] = '3b209906a533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_type', sa.String(length=100), nullable=False))
    op.add_column('appointments', sa.Column('visit_mode', sa.Enum('IN_PERSON', 'TELEHEALTH', name='visitmode'), nullable=False))
    op.drop_index(op.f('ix_appointments_priority_level'), table_name='appointments')
    op.drop_column('appointments', 'type')
    op.drop_column('appointments', 'no_show_count')
    op.drop_column('appointments', 'reminder_sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminder_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('no_show_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_appointments_priority_level'), 'appointments', ['priority_level'], unique=False)
    op.drop_column('appointments', 'visit_mode')
    op.drop_column('appointments', 'appointment_type')
    # ### end Alembic commands ###
