"""modularize_patient_and_agent_models

Revision ID: 8cf31c9c4c06
Revises: e95e82e7a258
Create Date: 2026-01-14 09:20:45.911887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf31c9c4c06'
down_revision: Union[str, Sequence[str], None] = 'e95e82e7a258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hiv_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_diagnosis', sa.Date(), nullable=True),
    sa.Column('art_start_date', sa.Date(), nullable=True),
    sa.Column('baseline_viral_load', sa.Integer(), nullable=True),
    sa.Column('baseline_cd4_count', sa.Integer(), nullable=True),
    sa.Column('initial_art_regimen', sa.String(length=255), nullable=True),
    sa.Column('current_art_regimen', sa.String(length=255), nullable=True),
    sa.Column('last_refill_date', sa.Date(), nullable=True),
    sa.Column('refill_months', sa.Integer(), nullable=True),
    sa.Column('next_refill_date', sa.Date(), nullable=True),
    sa.Column('last_viral_load_sample_date', sa.Date(), nullable=True),
    sa.Column('last_viral_load_result_date', sa.Date(), nullable=True),
    sa.Column('last_viral_load_result', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiv_profiles_patient_id'), 'hiv_profiles', ['patient_id'], unique=True)
    op.drop_column('patients', 'last_viral_load_result_date')
    op.drop_column('patients', 'date_of_diagnosis')
    op.drop_column('patients', 'initial_art_regimen')
    op.drop_column('patients', 'last_refill_date')
    op.drop_column('patients', 'art_start_date')
    op.drop_column('patients', 'baseline_cd4_count')
    op.drop_column('patients', 'current_art_regimen')
    op.drop_column('patients', 'next_refill_date')
    op.drop_column('patients', 'baseline_viral_load')
    op.drop_column('patients', 'last_viral_load_sample_date')
    op.drop_column('patients', 'refill_months')
    op.drop_column('patients', 'last_viral_load_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('last_viral_load_result', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('refill_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('last_viral_load_sample_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('baseline_viral_load', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('next_refill_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('current_art_regimen', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('baseline_cd4_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('art_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('last_refill_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('initial_art_regimen', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('date_of_diagnosis', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('last_viral_load_result_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hiv_profiles_patient_id'), table_name='hiv_profiles')
    op.drop_table('hiv_profiles')
    # ### end Alembic commands ###
