"""add all models

Revision ID: b4859c1ee12f
Revises: 8cf31c9c4c06
Create Date: 2026-01-20 15:23:21.598947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4859c1ee12f'
down_revision: Union[str, Sequence[str], None] = '8cf31c9c4c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_time'), 'appointments', ['scheduled_time'], unique=False)
    op.create_table('diabetes_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_diagnosis', sa.Date(), nullable=True),
    sa.Column('diabetes_type', sa.String(length=20), nullable=True),
    sa.Column('baseline_hba1c', sa.Float(), nullable=True),
    sa.Column('target_hba1c', sa.Float(), nullable=True),
    sa.Column('baseline_fasting_glucose', sa.Float(), nullable=True),
    sa.Column('target_fasting_glucose', sa.Float(), nullable=True),
    sa.Column('current_treatment', sa.String(length=255), nullable=True),
    sa.Column('insulin_regimen', sa.String(length=255), nullable=True),
    sa.Column('last_hba1c_date', sa.Date(), nullable=True),
    sa.Column('last_hba1c_result', sa.Float(), nullable=True),
    sa.Column('last_eye_exam_date', sa.Date(), nullable=True),
    sa.Column('last_foot_exam_date', sa.Date(), nullable=True),
    sa.Column('last_kidney_function_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetes_profiles_patient_id'), 'diabetes_profiles', ['patient_id'], unique=True)
    op.create_table('hypertension_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_diagnosis', sa.Date(), nullable=True),
    sa.Column('baseline_systolic', sa.Integer(), nullable=True),
    sa.Column('baseline_diastolic', sa.Integer(), nullable=True),
    sa.Column('target_systolic', sa.Integer(), nullable=True),
    sa.Column('target_diastolic', sa.Integer(), nullable=True),
    sa.Column('current_medication', sa.String(length=255), nullable=True),
    sa.Column('medication_start_date', sa.Date(), nullable=True),
    sa.Column('has_diabetes', sa.Boolean(), nullable=False),
    sa.Column('has_kidney_disease', sa.Boolean(), nullable=False),
    sa.Column('has_heart_disease', sa.Boolean(), nullable=False),
    sa.Column('last_checkup_date', sa.Date(), nullable=True),
    sa.Column('next_checkup_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypertension_profiles_patient_id'), 'hypertension_profiles', ['patient_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypertension_profiles_patient_id'), table_name='hypertension_profiles')
    op.drop_table('hypertension_profiles')
    op.drop_index(op.f('ix_diabetes_profiles_patient_id'), table_name='diabetes_profiles')
    op.drop_table('diabetes_profiles')
    op.drop_index(op.f('ix_appointments_scheduled_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
