"""fix_missing_timezone_column

Revision ID: ea22a49ee279
Revises: 31f012af3382
Create Date: 2026-01-27 00:20:46.923036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea22a49ee279'
down_revision: Union[str, Sequence[str], None] = '31f012af3382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if timezone column exists before adding it
    # This handles cases where the DB is out of sync with migrations
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('patients')]
    
    if 'timezone' not in columns:
        op.add_column('patients', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    
    if 'preferred_contact_method' not in columns:
         # In case it was missing too, though it should be there
         pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
