"""add decision summary field

Revision ID: f1765967927e
Revises: ae19f873840b
Create Date: 2026-02-01 07:27:19.612962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1765967927e'
down_revision: Union[str, Sequence[str], None] = 'ae19f873840b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_actions_session', 'call_actions', ['call_session_id'], unique=False)
    op.create_index('idx_call_actions_type', 'call_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_call_actions_call_session_id'), 'call_actions', ['call_session_id'], unique=False)
    op.drop_index(op.f('ix_appointments_priority_level'), table_name='appointments')
    op.drop_column('appointments', 'reminder_sent_at')
    op.drop_column('appointments', 'no_show_count')
    op.add_column('organizations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'onboarding_completed_at')
    op.drop_column('organizations', 'address')
    op.add_column('appointments', sa.Column('no_show_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('reminder_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_appointments_priority_level'), 'appointments', ['priority_level'], unique=False)
    op.drop_index(op.f('ix_call_actions_call_session_id'), table_name='call_actions')
    op.drop_index('idx_call_actions_type', table_name='call_actions')
    op.drop_index('idx_call_actions_session', table_name='call_actions')
    op.drop_table('call_actions')
    # ### end Alembic commands ###
