import uuid
import enum
from datetime import datetime

from sqlalchemy import (
    String, Text, Boolean, Integer, Float, DateTime, ForeignKey, Enum
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_model import BaseModel


class AlertSeverity(str, enum.Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    URGENT = "urgent"
    CRITICAL = "critical"


class AlertStatus(str, enum.Enum):
    """Alert handling status."""
    PENDING = "pending"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    ESCALATED = "escalated"


class Alert(BaseModel):
    """Alerts generated by the system or AI agent."""
    __tablename__ = "alerts"
    
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    patient_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("patients.id", ondelete="CASCADE"), index=True)
    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    health_reading_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("health_readings.id", ondelete="SET NULL"))
    
    # Alert
    severity: Mapped[AlertSeverity] = mapped_column(Enum(AlertSeverity), index=True)
    status: Mapped[AlertStatus] = mapped_column(Enum(AlertStatus), default=AlertStatus.PENDING, index=True)
    title: Mapped[str] = mapped_column(String(255))
    description: Mapped[str | None] = mapped_column(Text)
    
    # AI
    ai_assessment: Mapped[dict | None] = mapped_column(JSONB)
    recommended_actions: Mapped[list] = mapped_column(JSONB, default=list)
    
    # Resolution
    acknowledged_by_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resolved_by_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resolution_notes: Mapped[str | None] = mapped_column(Text)
    
    # Relationships
    patient = relationship("Patient", back_populates="alerts")
    organization = relationship("Organization")
    health_reading = relationship("HealthReading")
    acknowledged_by = relationship("User", foreign_keys=[acknowledged_by_id])
    resolved_by = relationship("User", foreign_keys=[resolved_by_id])


class AgentAction(BaseModel):
    """Actions taken by the AI health agent."""
    __tablename__ = "agent_actions"
    
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    patient_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("patients.id", ondelete="CASCADE"), index=True)
    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    triggered_by_reading_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("health_readings.id", ondelete="SET NULL"))
    triggered_by_alert_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("alerts.id", ondelete="SET NULL"))
    
    # Action
    action_type: Mapped[str] = mapped_column(String(50), index=True)
    status: Mapped[str] = mapped_column(String(20), default="pending", index=True)
    content: Mapped[dict | None] = mapped_column(JSONB)
    recipient: Mapped[str | None] = mapped_column(String(255))
    
    # Execution
    scheduled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    executed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    result: Mapped[dict | None] = mapped_column(JSONB)
    error_message: Mapped[str | None] = mapped_column(Text)
    retry_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # AI
    ai_reasoning: Mapped[str | None] = mapped_column(Text)
    confidence_score: Mapped[float | None] = mapped_column(Float)
    
    # Relationships
    patient = relationship("Patient", back_populates="agent_actions")
    organization = relationship("Organization")
    triggered_by_reading = relationship("HealthReading")
    triggered_by_alert = relationship("Alert")


class ScheduledCheck(BaseModel):
    """Scheduled health checks for patients."""
    __tablename__ = "scheduled_checks"
    
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    patient_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("patients.id", ondelete="CASCADE"), index=True)
    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"))
    
    # Schedule
    check_type: Mapped[str] = mapped_column(String(50))
    scheduled_time: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    recurrence: Mapped[str | None] = mapped_column(String(50))
    recurrence_config: Mapped[dict | None] = mapped_column(JSONB)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, index=True)
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    next_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    
    # Relationships
    patient = relationship("Patient")
    organization = relationship("Organization")
